name: tesseratjs_dart
description: Dart wrapper for tesseractjs.
version: 1.0.0
homepage: https://github.com/Hecatoncheir/tesseractjs_dart

environment:
  sdk: ^3.2.0

dependencies:
  js: ^0.6.7

dev_dependencies:
  lints: ^3.0.0
  dart_code_metrics: ^5.7.6
